### ISSUE TITLE
Feature Request: Custom Boards

### ISSUE THREAD

**Issue by FruitJuice** [d0x2f/retro.tools#159]
Just to be able to define custom columns, templates. Could be a list of columns with comma separated and create a board based on that.

**Comment by d0x2f** [comment]
I've done a lot of work this, it's not live at retro.tools yet, but you can try it out [here](https://retrotools-284402--feature-custom-columns-316ueroj.web.app).

You can click the column icon to open a settings drawer where you can change the name, colour and icon.

![image](https://user-images.githubusercontent.com/8149130/226214920-8cc4764c-6c4c-4cf3-9314-2dc47c6ba877.png)

You can also delete the column with the trash can icon to the right of the card input box.

To add a column, use the drop down on the top right.

![image](https://user-images.githubusercontent.com/8149130/226215001-914dbfe8-f17f-4844-8da9-64628a3a1d58.png)

You can have up to 6 columns.

I'm just writting tests and tweaking now, so hopefully it'll be deployed within a few days.

Let me know if you have any feedback!

**Comment by d0x2f** [comment]
Deployed :tada:
